### PR TITLE
Revert back USIR Data Catalog to use its own spark cluster

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Review by accorvin — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]

**Comment by rimolive** [comment]
ping @harshad16 . Can you take a look why this PR is taking to long in the pre-commit checks?

**Comment by harshad16** [comment]
> Can you take a look why this PR is taking to long in the pre-commit checks?

Sure the ci is under pressure, too many requests, it is trying to full fill them.

**Comment by harshad16** [comment]
there so many request the app is serving , this will take more time
Manual merging would be recommended if this is needed sooner.

**Comment by rimolive** [comment]
We can wait as the changes are already applied. This merge will just make the project in ArgoCD get synced again.

**Pull request merged**
