### PR TITLE
Add MySQL exporter secret to production environment

### PR DESCRIPTION
**Pull request by rimolive**
This will fix the access denied errors from the logs

### CODE REVIEW

**Comment by anishasthana** [comment]
@rimolive The build is not succeeding

**Review by anishasthana — APPROVED** [review]
Build succeeds, the password looks like it was generated correctly.

**Review by accorvin — COMMENTED** [review]
Do we need these changes for all of the overlay environments?

**Review by maulikjs — APPROVED** [review]

**Pull request merged**
