### PR TITLE
feat: Remove Argo-Events

### PR DESCRIPTION
**Pull request by tumido**
Fully cleanup Argo Events manifest

~Merge after: https://github.com/AICoE/aicoe-cd/pull/276 https://github.com/AICoE/aicoe-cd/pull/277~

### CODE REVIEW

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
Thanks @tumido !

**Pull request merged**
