### PR TITLE
Presto

### PR DESCRIPTION
**Pull request by maulikjs**
This MR adds the dev resources to deploy presto.

To test run: 
```
kustomize build --enable_alpha_plugins presto/overlays/dev
```

### CODE REVIEW

**Comment by HumairAK** [comment]
can you fix the pre-commit errors : )

**Comment by maulikjs** [comment]
@sesheta retest

**Comment by HumairAK** [comment]
Can we get a README.md on deploy instructions, and a brief note to try again if it fails with the following error: 

```
error: unable to recognize "STDIN": no matches for kind "Presto" in version "starburstdata.com/v1"

```

**Review by HumairAK — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
