### PR TITLE
feat: Update Argo to 2.12.5 and use upstream images again

### PR DESCRIPTION
**Pull request by tumido**
This will make us use upstream images from [argoproj](https://quay.io/organization/argoproj) quay again + bumps the version few patch releases.

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
The build succeeded and the OpenShift objects look correct. Thanks Tom!

**Comment by tumido** [comment]
This PR will allow us to revert to upstream images and cleanup the odh quay repo duplicity. We'll match current ODH master with this PR.

The this patch release doesn't fix the "forbidden" cosmetic bug mentioned at https://github.com/opendatahub-io/odh-manifests/pull/208

**Comment by anishasthana** [comment]
@tumido the commits here look.... odd

**Comment by tumido** [comment]
@anishasthana I think @goern just rebased my PR using the GitHub button, which is usually on the same place as the "Merge" button. I don't see any harm in the commit though. I bet @goern doesn't mean to sabotage this PR. :smile:

**Comment by goern** [comment]
Ja 😁

**Comment by tumido** [comment]
Seems like Prow is on fire because of this PR for some reason:
image


Closing for now and hoping it'll help.

**Review by gmfrasca — APPROVED** [review]

**Pull request merged**
